In [1]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [2]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [3]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [4]:
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [5]:
base = pd.read_csv('house_prices.csv', usecols = colunas_usadas)

In [6]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

In [8]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [9]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [10]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [11]:
X = base.drop('price', axis = 1)
y = base.price

In [12]:
X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [13]:
type(X)

pandas.core.frame.DataFrame

In [14]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [15]:
type(y)

pandas.core.series.Series

In [16]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [ ]:
import tensorflow as tf

In [18]:
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [19]:
print(colunas[10])

_NumericColumn(key='sqft_basement', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [20]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [21]:
X_treinamento.shape

(15129, 16)

In [22]:
y_treinamento.shape

(15129,)

In [23]:
X_teste.shape

(6484, 16)

In [24]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = X_treinamento, y = y_treinamento,
                                                        batch_size = 32, num_epochs = None, shuffle = True)

In [25]:
funcao_teste = tf.estimator.inputs.pandas_input_fn(x = X_teste, y = y_teste,
                                                   batch_size = 32, num_epochs = 10000, shuffle = False)

In [26]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmpg5rbonoy', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1a29f60f28>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [27]:
regressor.train(input_fn=funcao_treinamento, steps = 10000)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmpg5rbonoy/model.ckpt.
INFO:tensorflow:loss = 0.11676359, step = 1
INFO:tensorflow:global_step/sec: 298.23
INFO:tensorflow:loss = 0.022799991, step = 101 (0.337 sec)
INFO:tensorflow:global_step/sec: 379.318
INFO:tensorflow:loss = 0.014103654, step = 201 (0.263 sec)
INFO:tensorflow:global_step/sec: 361.664
INFO:tensorflow:loss = 0.018615434, step = 301 (0.277 sec)
INFO:tensorflow:global_step/sec: 375.55
INFO:tensorf

INFO:tensorflow:global_step/sec: 394.727
INFO:tensorflow:loss = 0.049398404, step = 6901 (0.255 sec)
INFO:tensorflow:global_step/sec: 382.131
INFO:tensorflow:loss = 0.034167066, step = 7001 (0.262 sec)
INFO:tensorflow:global_step/sec: 378.607
INFO:tensorflow:loss = 0.01938305, step = 7101 (0.264 sec)
INFO:tensorflow:global_step/sec: 389.587
INFO:tensorflow:loss = 0.016076045, step = 7201 (0.258 sec)
INFO:tensorflow:global_step/sec: 416.288
INFO:tensorflow:loss = 0.0103822155, step = 7301 (0.240 sec)
INFO:tensorflow:global_step/sec: 406.842
INFO:tensorflow:loss = 0.009721854, step = 7401 (0.245 sec)
INFO:tensorflow:global_step/sec: 404.935
INFO:tensorflow:loss = 0.023101095, step = 7501 (0.247 sec)
INFO:tensorflow:global_step/sec: 412.028
INFO:tensorflow:loss = 0.024339858, step = 7601 (0.243 sec)
INFO:tensorflow:global_step/sec: 414.253
INFO:tensorflow:loss = 0.011962777, step = 7701 (0.242 sec)
INFO:tensorflow:global_step/sec: 401.749
INFO:tensorflow:loss = 0.0058343075, step = 7801 (

In [28]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-11-08-22:00:24
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmpg5rbonoy/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2018-11-08-22:00:48
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0006959648, global_step = 10000, label/mean = 0.06121547, loss = 0.022270873, prediction/mean = 0.06

In [29]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-11-08-22:00:49
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmpg5rbonoy/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2018-11-08-22:01:13
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00073397084, global_step = 10000, label/mean = 0.06050085, loss = 0.023487067, prediction/mean = 0.0

In [30]:
metricas_treinamento

{'average_loss': 0.0006959648,
 'label/mean': 0.06121547,
 'loss': 0.022270873,
 'prediction/mean': 0.061249834,
 'global_step': 10000}

In [31]:
metricas_teste

{'average_loss': 0.00073397084,
 'label/mean': 0.06050085,
 'loss': 0.023487067,
 'prediction/mean': 0.060595818,
 'global_step': 10000}

In [32]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = X_teste, shuffle = False)

In [33]:
previsoes = regressor.predict(input_fn=funcao_previsao)

In [34]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmpg5rbonoy/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.07866833], dtype=float32)},
 {'predictions': array([0.03514604], dtype=float32)},
 {'predictions': array([0.00147246], dtype=float32)},
 {'predictions': array([0.11240721], dtype=float32)},
 {'predictions': array([0.02862398], dtype=float32)},
 {'predictions': array([0.03586603], dtype=float32)},
 {'predictions': array([0.13500354], dtype=float32)},
 {'predictions': array([0.04787365], dtype=float32)},
 {'predictions': array([0.04210912], dtype=float32)},
 {'predictions': array([0.03070981], dtype=float32)},
 {'predictions': array([0.02599271], dtype=float32)},
 {'predictions': array([0.0366342], dtype=float32)},
 {'predictions': array([0.08990083], dtype=float32)},
 {'predictions': array([0.03648183], dtype=float32)},
 {'predictions': array([0.05588827], dtype=float32)},
 {'predictions': array([0.0614598], dtype=float32)},
 {'predictions': array([0.05233657], dtype=float32)},
 {'predictions': array([0.03540197], dtype=float32)},
 {'predictions': array([0.0404

In [35]:
valores_previsoes = []
for p in regressor.predict(input_fn=funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmpg5rbonoy/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [36]:
valores_previsoes

[array([0.07866833], dtype=float32),
 array([0.03514604], dtype=float32),
 array([0.00147246], dtype=float32),
 array([0.11240721], dtype=float32),
 array([0.02862398], dtype=float32),
 array([0.03586603], dtype=float32),
 array([0.13500354], dtype=float32),
 array([0.04787365], dtype=float32),
 array([0.04210912], dtype=float32),
 array([0.03070981], dtype=float32),
 array([0.02599271], dtype=float32),
 array([0.0366342], dtype=float32),
 array([0.08990083], dtype=float32),
 array([0.03648183], dtype=float32),
 array([0.05588827], dtype=float32),
 array([0.0614598], dtype=float32),
 array([0.05233657], dtype=float32),
 array([0.03540197], dtype=float32),
 array([0.04044603], dtype=float32),
 array([0.15950224], dtype=float32),
 array([0.0580394], dtype=float32),
 array([0.0930642], dtype=float32),
 array([0.04095626], dtype=float32),
 array([0.03243885], dtype=float32),
 array([0.05372988], dtype=float32),
 array([0.12013542], dtype=float32),
 array([0.0328676], dtype=float32),
 array

In [37]:
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1,1)

In [38]:
valores_previsoes

array([[0.07866833],
       [0.03514604],
       [0.00147246],
       ...,
       [0.06333325],
       [0.06343665],
       [0.04504813]], dtype=float32)

In [39]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[674846.  ],
       [342988.6 ],
       [ 86227.49],
       ...,
       [557916.  ],
       [558704.44],
       [418491.97]], dtype=float32)

In [40]:
y_teste

8912     0.051148
8090     0.053836
14562    0.026754
8578     0.063607
9070     0.026098
15893    0.022295
15924    0.204721
16162    0.110164
16662    0.042885
15669    0.064918
10041    0.033443
10450    0.042951
15788    0.065180
18540    0.052459
12386    0.041967
10824    0.068702
11959    0.057043
9191     0.028590
4293     0.037220
16741    0.166951
15451    0.059148
4251     0.085246
13112    0.037377
6310     0.030905
2940     0.062295
4796     0.069508
16395    0.037574
17414    0.087082
15556    0.047862
11684    0.057049
           ...   
3135     0.026230
1589     0.033705
17187    0.059908
11810    0.046551
15572    0.033443
19495    0.023869
19936    0.061115
18606    0.162623
3470     0.053010
12098    0.018754
11072    0.028197
5008     0.095738
16301    0.200000
13030    0.032131
4260     0.054420
12117    0.066885
14796    0.047213
9492     0.040000
7155     0.022951
10667    0.083934
9901     0.086557
12371    0.078033
7901     0.040000
17005    0.084590
17043    0

In [41]:
y_teste.shape

(6484,)

In [42]:
y_teste2 = y_teste.values.reshape(-1,1)
y_teste2.shape

(6484, 1)

In [43]:
y_teste2 = scaler_y.inverse_transform(y_teste2)

In [44]:
y_teste2

array([[465000.],
       [485500.],
       [279000.],
       ...,
       [680000.],
       [443000.],
       [349950.]])

In [45]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsoes)

In [46]:
mae

130825.09389628576